package me.manga.kira.backend.sourceconfig.validation

/**
 * Stable machine identifiers for every validation finding (PLAN §8). Codes are part of the API
 * contract (`errors[].code`), so they must remain stable across releases. Names ending the plan's
 * explicitly-mandated identifiers verbatim (`DUPLICATE_API`, `UNKNOWN_TRANSFORM`, `FILTER_CYCLE`,
 * `GENERIC_MISSING_*`, `FORBIDDEN_HEADER`, `SECRET_LIKE_HEADER`, `URL_USERINFO_FORBIDDEN`,
 * `UNKNOWN_ICON_KEY`); the rest are the server's stable choices for rules the plan left un-named.
 *
 * The trailing comment on each is the PLAN §8 rule number it enforces.
 */
object ValidationCodes {
    // Document level
    const val UNSUPPORTED_SCHEMA_VERSION = "UNSUPPORTED_SCHEMA_VERSION" // rule 1
    const val DUPLICATE_API = "DUPLICATE_API" // rule 2

    // Every source (any engine)
    const val API_BLANK = "API_BLANK" // rule 3
    const val LANGUAGE_BLANK = "LANGUAGE_BLANK" // rule 4
    const val BASE_URL_NOT_HTTP = "BASE_URL_NOT_HTTP" // rule 5
    const val UNKNOWN_ENGINE = "UNKNOWN_ENGINE" // rule 6
    const val UNKNOWN_SITE_STATE = "UNKNOWN_SITE_STATE" // rule 7
    const val UNKNOWN_LIFECYCLE = "UNKNOWN_LIFECYCLE" // rule 8
    const val HOST_NOT_BARE = "HOST_NOT_BARE" // rule 9
    const val ICON_RESOURCE_KEY_INVALID = "ICON_RESOURCE_KEY_INVALID" // rule 10
    const val ICON_REMOTE_URL_NOT_HTTPS = "ICON_REMOTE_URL_NOT_HTTPS" // rule 10
    const val ICON_EMPTY = "ICON_EMPTY" // rule 10
    const val FILTERS_NOT_ALLOWED_FOR_ENGINE = "FILTERS_NOT_ALLOWED_FOR_ENGINE" // rule 11

    // Generic-engine sources only
    const val UNKNOWN_PAGINATION_TYPE = "UNKNOWN_PAGINATION_TYPE" // rule 12
    const val GENERIC_MISSING_HOME_OR_FEATURED = "GENERIC_MISSING_HOME_OR_FEATURED" // rules 13 & 31
    const val ENDPOINT_URL_BLANK = "ENDPOINT_URL_BLANK" // rule 14
    const val ENDPOINT_URL_RAW_QUERY = "ENDPOINT_URL_RAW_QUERY" // rule 14
    const val ENDPOINT_JSONBODY_RAW_QUERY = "ENDPOINT_JSONBODY_RAW_QUERY" // rule 14
    const val ENDPOINT_UNKNOWN_METHOD = "ENDPOINT_UNKNOWN_METHOD" // rule 14
    const val ENDPOINT_UNKNOWN_FORMAT = "ENDPOINT_UNKNOWN_FORMAT" // rule 14
    const val LISTFILTER_UNKNOWN_OP = "LISTFILTER_UNKNOWN_OP" // rule 14
    const val LISTFILTER_UNKNOWN_MODE = "LISTFILTER_UNKNOWN_MODE" // rule 14
    const val UNKNOWN_TRANSFORM = "UNKNOWN_TRANSFORM" // rule 15
    const val UNKNOWN_DATE_STRATEGY = "UNKNOWN_DATE_STRATEGY" // rule 15
    const val IMAGE_STRATEGY_NOT_ALLOWED = "IMAGE_STRATEGY_NOT_ALLOWED" // rule 15

    // Search filters (generic only)
    const val FILTER_ID_INVALID = "FILTER_ID_INVALID" // rule 16
    const val FILTER_ID_DUPLICATE = "FILTER_ID_DUPLICATE" // rule 16
    const val FILTER_LABEL_BLANK = "FILTER_LABEL_BLANK" // rule 17
    const val FILTER_UNKNOWN_TYPE = "FILTER_UNKNOWN_TYPE" // rule 18
    const val FILTER_TYPE_PINNING = "FILTER_TYPE_PINNING" // rule 19
    const val FILTER_OPTIONS_REQUIRED = "FILTER_OPTIONS_REQUIRED" // rule 20
    const val FILTER_OPTIONS_FORBIDDEN = "FILTER_OPTIONS_FORBIDDEN" // rule 20
    const val FILTER_OPTION_VALUE_BLANK = "FILTER_OPTION_VALUE_BLANK" // rule 20
    const val FILTER_OPTION_VALUE_DUPLICATE = "FILTER_OPTION_VALUE_DUPLICATE" // rule 20
    const val FILTER_DEFAULTS_NOT_ALLOWED = "FILTER_DEFAULTS_NOT_ALLOWED" // rule 21
    const val FILTER_DEFAULT_NOT_ALLOWED = "FILTER_DEFAULT_NOT_ALLOWED" // rule 21 (multiselect must not set `default`)
    const val FILTER_DEFAULT_NOT_OPTION = "FILTER_DEFAULT_NOT_OPTION" // rule 21
    const val FILTER_TOGGLE_DEFAULT_INVALID = "FILTER_TOGGLE_DEFAULT_INVALID" // rule 21
    const val FILTER_NUMBER_DEFAULT_INVALID = "FILTER_NUMBER_DEFAULT_INVALID" // rule 21
    const val FILTER_REQUIRED_WITHOUT_DEFAULT = "FILTER_REQUIRED_WITHOUT_DEFAULT" // rule 21
    const val FILTER_REQUEST_UNKNOWN_TARGET = "FILTER_REQUEST_UNKNOWN_TARGET" // rule 22
    const val FILTER_REQUEST_PARAM_BLANK = "FILTER_REQUEST_PARAM_BLANK" // rule 22
    const val FILTER_REQUEST_UNKNOWN_ENCODE = "FILTER_REQUEST_UNKNOWN_ENCODE" // rule 22
    const val FILTER_ENCODE_INCOMPATIBLE = "FILTER_ENCODE_INCOMPATIBLE" // rule 22
    const val FILTER_PARAM_INVALID = "FILTER_PARAM_INVALID" // rule 23
    const val FILTER_PARAM_RESERVED = "FILTER_PARAM_RESERVED" // rule 23
    const val FILTER_PATH_REQUIRES_DEFAULT = "FILTER_PATH_REQUIRES_DEFAULT" // rules 23 & 24
    const val FILTER_APPLIES_TO_EMPTY = "FILTER_APPLIES_TO_EMPTY" // rule 24
    const val FILTER_APPLIES_TO_UNKNOWN_VERB = "FILTER_APPLIES_TO_UNKNOWN_VERB" // rule 24
    const val FILTER_ENDPOINT_MISSING = "FILTER_ENDPOINT_MISSING" // rule 24
    const val FILTER_FORM_METHOD_MISMATCH = "FILTER_FORM_METHOD_MISMATCH" // rule 24
    const val FILTER_FORM_PARAM_COLLISION = "FILTER_FORM_PARAM_COLLISION" // rule 24
    const val FILTER_BODYJSON_METHOD_MISMATCH = "FILTER_BODYJSON_METHOD_MISMATCH" // rule 24
    const val FILTER_BODYJSON_MISSING_PLACEHOLDER = "FILTER_BODYJSON_MISSING_PLACEHOLDER" // rule 24
    const val FILTER_PATH_PLACEHOLDER_MISSING = "FILTER_PATH_PLACEHOLDER_MISSING" // rule 24
    const val FILTER_QUERY_PARAM_HARDCODED = "FILTER_QUERY_PARAM_HARDCODED" // rule 24
    const val FILTER_VISIBLEWHEN_UNKNOWN = "FILTER_VISIBLEWHEN_UNKNOWN" // rule 25
    const val FILTER_VISIBLEWHEN_SELF = "FILTER_VISIBLEWHEN_SELF" // rule 25
    const val FILTER_VISIBLEWHEN_EMPTY_ANYOF = "FILTER_VISIBLEWHEN_EMPTY_ANYOF" // rule 25
    const val FILTER_VISIBLEWHEN_OUT_OF_VOCABULARY = "FILTER_VISIBLEWHEN_OUT_OF_VOCABULARY" // rule 25
    const val FILTER_EXCLUDEOF_NOT_MULTISELECT = "FILTER_EXCLUDEOF_NOT_MULTISELECT" // rule 26
    const val FILTER_EXCLUDEOF_SELF = "FILTER_EXCLUDEOF_SELF" // rule 26
    const val FILTER_EXCLUDEOF_UNKNOWN = "FILTER_EXCLUDEOF_UNKNOWN" // rule 26
    const val FILTER_EXCLUDEOF_TARGET_NOT_MULTISELECT = "FILTER_EXCLUDEOF_TARGET_NOT_MULTISELECT" // rule 26
    const val FILTER_EXCLUDEOF_CHAINED = "FILTER_EXCLUDEOF_CHAINED" // rule 26
    const val FILTER_EXCLUDEOF_DEFAULTS_OVERLAP = "FILTER_EXCLUDEOF_DEFAULTS_OVERLAP" // rule 26
    const val FILTER_CYCLE = "FILTER_CYCLE" // rule 27

    // Server-additional rules (31–33)
    const val GENERIC_MISSING_SEARCH = "GENERIC_MISSING_SEARCH" // rule 31
    const val GENERIC_MISSING_DETAILS = "GENERIC_MISSING_DETAILS" // rule 31
    const val GENERIC_MISSING_PAGES = "GENERIC_MISSING_PAGES" // rule 31
    const val HEADER_NAME_INVALID = "HEADER_NAME_INVALID" // rule 32: RFC field-name token
    const val FORBIDDEN_HEADER = "FORBIDDEN_HEADER" // rule 32a
    const val SECRET_LIKE_HEADER = "SECRET_LIKE_HEADER" // rule 32b
    const val URL_INVALID = "URL_INVALID" // rule 32c
    const val URL_SCHEME_INVALID = "URL_SCHEME_INVALID" // rule 32c
    const val URL_USERINFO_FORBIDDEN = "URL_USERINFO_FORBIDDEN" // rule 32c
    const val URL_FRAGMENT_FORBIDDEN = "URL_FRAGMENT_FORBIDDEN" // rule 32c
    const val URL_HOST_MISSING = "URL_HOST_MISSING" // rule 32c

    const val UNKNOWN_ICON_KEY = "UNKNOWN_ICON_KEY" // rule 33 (warning)
}
