server {
    listen 80;
    listen [::]:80;
    server_name kiramanga.me www.kiramanga.me;
    location ^~ /.well-known/acme-challenge/ { root /var/www/letsencrypt; }
    location / { return 301 https://kiramanga.me$request_uri; }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.kiramanga.me;
    ssl_certificate /etc/letsencrypt/live/kiramanga.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kiramanga.me/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    return 301 https://kiramanga.me$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name kiramanga.me;
    ssl_certificate /etc/letsencrypt/live/kiramanga.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kiramanga.me/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:18081;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

