package me.manga.kira.backend.common.infrastructure.persistence

internal const val BOOTSTRAP_VERIFIED_EXIT = 61
internal const val BOOTSTRAP_DRIVER_MARKER = "kira.synthetic.bootstrap.driver.initialized"
internal const val BOOTSTRAP_BUNDLE_MARKER = "kira.synthetic.bootstrap.bundle.initialized"
internal const val BOOTSTRAP_LEAF = "org.postgresql.jdbc.BooleanTypeUtil"
internal const val BOOTSTRAP_CANARY = "BOOTSTRAP_SYNTHETIC_CANARY"
internal const val BOOTSTRAP_READY_FILE = "bootstrap.ready"
internal const val BOOTSTRAP_READY_PENDING_FILE = "bootstrap.ready.pending"
internal const val BOOTSTRAP_READY_MAX_BYTES = 256

enum class BootstrapProbeCase {
    REAL_CONSTRUCTION,
    COLD_SYNTHETIC,
    WRONG_TYPE,
    MISSING_CLASS,
    PRIVATE_CONSTRUCTOR,
    DEFAULT_RESOURCE_CHILD,
    DEFAULT_RESOURCE_ABSENT,
    DEFAULT_RESOURCE_SYSTEM,
    RESOURCE_IO_FAILURE,
    RESOURCE_INTERRUPTED,
    RESOURCE_FATAL,
    DRIVER_LINKAGE_FATAL,
    OWNER_LOADER_FAILURE,
    OWNER_LOADER_FATAL,
    CONSTRUCTOR_FAILURE,
    CONSTRUCTOR_INTERRUPTED,
    CONSTRUCTOR_FATAL,
    HIDDEN_CONFIG_PRESENT,
    HIDDEN_CONFIG_EMPTY,
    HIDDEN_LOOKALIKE,
    WRITER,
    LEGACY_WRITER,
    NO_DISCOVERY,
    JUL_LEVEL_MATRIX,
    JUL_ANCESTOR_LATENT,
    JUL_EXISTING_CHILD,
    JUL_FILTER_NOT_AUTHORITY,
    JUL_CUSTOM_LOGGER,
    JUL_CUSTOM_ANCESTOR,
    JUL_CUSTOM_MANAGER,
    JUL_FOREIGN_DESCENDANT,
    JUL_CONFIGURED_ANCESTOR_FOREIGN,
    JUL_UNRELATED_CUSTOM,
    JUL_TARGET_HANDLER,
    JUL_ANCESTOR_HANDLER,
    JUL_EMPTY_HANDLER,
    JUL_LOCALIZED_C1,
    LOGBACK_LEVEL_MATRIX,
    LOGBACK_LATE_CHILD,
    LOGBACK_FILTER,
    UNKNOWN_FACTORY,
    NOP_FACTORY,
    UNKNOWN_CONTEXT,
    UNFINISHED_FACTORY,
    GLOBAL_DRIFT,
    JUL_DRIFT,
    LOGBACK_DRIFT,
    PENDING_LEVEL,
    ASSERTION_FAILURE,
    WAIT_FOR_TERMINATION,
    NOOP_EXIT,
    WRONG_RECEIPT,
    EXTRA_ENVIRONMENT,
    WRONG_READY_IDENTITY,
}
